In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# import numpy as np


arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
###NUMPY VECTORIZRED operation

In [18]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("addition:", arr1 + arr2)
print("substraction:", arr1 - arr2)


addition: [11 22 33 44]
substraction: [ -9 -18 -27 -36]


In [ ]:
#universal function
arr= np.array([2,3,4,5,6,7])

#sqaure rorot
print(np.sqrt(arr))

#exponent

